### ISSUE TITLE
Getting Continuous Key Error after upgrading from v2 to v4

### ISSUE THREAD

**Issue by jaspreet-singh37349** [NishargShah/react-img-mapper#1]
**Describe the bug**

I am getting continuous key uniqueness error from your module

**To Reproduce**

1. passing map area causing the error

**Error Stack**

> Encountered two children with the same key, `03`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

**Expected behavior**

Not getting error

**Screenshots**

![image](https://user-images.githubusercontent.com/35843261/105707222-9fe00c80-5f38-11eb-9abb-b5879769ff62.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: 86

**JSON**

```
[
  {
    "id": "<AutoIncrementValue>",
    "title": "title",
    "shape": "poly",
    "name": "name",
    "fillColor": "skyblue",
    "strokeColor": "black",
    "coords": [<MyCoords>]
  },
  ....
]
```

**Comment by NishargShah** [comment]
The problem is in your `id`, your `id` is not unique and as docs said `id` must be unique but you can change that behavior by changing the key name

```
areaKeyName: '<uniqueId>'
```

so add `unique` key name in your JSON and your error will go, else you can specify any name on it such as `areaKeyName: 'index'` so it will take `index` of the array as your key.

```
[
  {
    "id": "<AutoIncrementValue>",
    "<uniqueKey>": "<unique>",
    "title": "title",
    "shape": "poly",
    "name": "name",
    "fillColor": "skyblue",
    "strokeColor": "black",
    "coords": [<MyCoords>]
  },
  ....
]
```
